apiVersion: batch/v1
kind: Job
metadata:
  name: eat-one-a
spec:
  parallelism: 3
  completions: 6
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: eat
      labels:
        user: one
        zone: a
    spec:
      containers:
        - name: eat
          image: resource-eater:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/eat"
            - "480"
            - "1"
      restartPolicy: OnFailure
---

apiVersion: batch/v1
kind: Job
metadata:
  name: eat-one-b
spec:
  parallelism: 3
  completions: 12
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: eat
      labels:
        user: one
        zone: b
    spec:
      containers:
        - name: eat
          image: resource-eater:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/eat"
            - "360"
            - "1"
      restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: Job
metadata:
  name: eat-two-a
spec:
  parallelism: 3
  completions: 9
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: eat
      labels:
        user: two
        zone: a
    spec:
      containers:
        - name: eat
          image: resource-eater:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/eat"
            - "360"
            - "2"
      restartPolicy: OnFailure
